language_index:
    path:     /
    defaults: { _controller: "WCSLyonGameBundle:Language:index" }
    methods:  GET

language_show:
    path:     /{id}/show
    defaults: { _controller: "WCSLyonGameBundle:Language:show" }
    methods:  GET

language_new:
    path:     /new
    defaults: { _controller: "WCSLyonGameBundle:Language:new" }
    methods:  [GET, POST]

language_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSLyonGameBundle:Language:edit" }
    methods:  [GET, POST]

language_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSLyonGameBundle:Language:delete" }
    methods:  DELETE
