stopover_index:
    path:     /
    defaults: { _controller: "WCSLyonGameBundle:StopOver:index" }
    methods:  GET

stopover_show:
    path:     /{id}/show
    defaults: { _controller: "WCSLyonGameBundle:StopOver:show" }
    methods:  GET

stopover_new:
    path:     /new
    defaults: { _controller: "WCSLyonGameBundle:StopOver:new" }
    methods:  [GET, POST]

stopover_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSLyonGameBundle:StopOver:edit" }
    methods:  [GET, POST]

stopover_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSLyonGameBundle:StopOver:delete" }
    methods:  DELETE
