WCS\LyonGameBundle\Entity\Language:
    type: entity
    table: null
    repositoryClass: WCS\LyonGameBundle\Repository\LanguageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lang:
            type: string
            length: '30'

    oneToMany:
        tripEnglishs:
            targetEntity: TripEnglish
            mappedBy: language

    lifecycleCallbacks: {  }
