WCS\LyonGameBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: WCS\LyonGameBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        email:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: '50'
        country:
            type: string
            length: 255
        city:
            type: string
            length: 255

    manyToOne:
            Language:
                targetEntity: Language
                inversedBy: users
                joinColumn:
                    name: language_id
                    referencedColumnName: id

    manyToMany:
            trips:
                targetEntity: Trip
                inversedBy: users
                joinTable:
                    name: users_trips
                    joinColumns:
                        user_id:
                            referencedColumnName: id
                    inverserJoinColumns:
                        trip_id:
                            referencedColumnName: id
    lifecycleCallbacks: {  }
